In [11]:
import geopandas
import shapely

In [12]:
joined = geopandas.read_file(r"/home/mohammad/w/AmlakNama/updateData/management/commands/shape_files/joined_poligon.shp")
joined

,caseid,NAME_MAHAL,reg_no,index_righ,landuse,ptype,mtrprice,cyear,crdatetime,geometry
0,15,ابن بابويه و ظهيرآباد,20,12,res,buy,66346000,۱۴۰۳,2024-12-08,"POLYGON ((540414.91 3940123.57, 540443.349 394..."
1,86,استخر,20,83,res,buy,74647000,۱۳۸۷,2024-10-13,"POLYGON ((540984.93 3938831.03, 540988.78 3938..."
2,1912,دولت آباد,20,1702,res,rent,28571,۱۳۸۵,2024-12-16,"POLYGON ((541206.567 3942435.722, 541342.519 3..."
3,456,دولت آباد,20,435,res,rent,15217391,۱۳۸۸,2024-10-13,"POLYGON ((541206.567 3942435.722, 541342.519 3..."
4,1302,دولت آباد,20,1222,res,rent,6400000,قبل از ۱۳۷۰,2024-12-15,"POLYGON ((541206.567 3942435.722, 541342.519 3..."
...,...,...,...,...,...,...,...,...,...,...
3231,1660,المهدي,5,1498,res,buy,78676000,۱۳۸۷,2024-12-15,"POLYGON ((530353.651 3959431.136, 530353.9 395..."
3232,3137,المهدي,5,2685,resland,buy,295,0,2025-11-06,"POLYGON ((530353.651 3959431.136, 530353.9 395..."
3233,291,المهدي,5,282,res,buy,73382000,۱۳۸۸,2024-10-14,"POLYGON ((530353.651 3959431.136, 530353.9 395..."
3234,3862,المهدي,5,3149,com,buy,760,۱۳۹۵,2025-11-07,"POLYGON ((530353.651 3959431.136, 530353.9 395..."
3235,455,المهدي,5,434,res,rent,13108108,۱۳۸۴,2024-10-13,"POLYGON ((530353.651 3959431.136, 530353.9 395..."

In [3]:
joined.drop(["Shape_Le_1","Shape_Area","index_righ"], inplace=True, axis=1)
joined.set_index('caseid', inplace=True)

KeyError: "['Shape_Le_1', 'Shape_Area'] not found in axis"

In [13]:
joined.set_index('caseid', inplace=True)

In [14]:
resbuy1 = joined.query("landuse == 'res' and ptype == 'buy' and reg_no == 1")
resbuy1

,NAME_MAHAL,reg_no,index_righ,landuse,ptype,mtrprice,cyear,crdatetime,geometry
caseid,,,,,,,,,
1400,ازگل,1,1311,res,buy,134782000,۱۴۰۳,2024-12-15,"POLYGON ((544638.41 3961937.689, 544823.668 39..."
1665,شهرک نفت,1,1503,res,buy,160000000,۱۴۰۳,2024-12-15,"POLYGON ((546597.381 3963216.63, 546636.82 396..."
4032,سوهانک,1,3248,res,buy,234,۱۴۰۰,2025-11-07,"POLYGON ((547286.649 3962795.369, 547302.97 39..."
3498,تجريش,1,2910,res,buy,250,۱۳۸۸,2025-11-07,"POLYGON ((538714.42 3962604.163, 538718.04 396..."
273,باغ فردوس,1,264,res,buy,315789000,۱۳۹۶,2024-10-14,"POLYGON ((537972.956 3962157.486, 538014.813 3..."
1306,زعفرانيه,1,1227,res,buy,200892000,۱۳۸۴,2024-12-15,"POLYGON ((538675.089 3962605.612, 538569.174 3..."
3131,زعفرانيه,1,2680,res,buy,256,۱۳۹۸,2025-11-06,"POLYGON ((538675.089 3962605.612, 538569.174 3..."
2735,زعفرانيه,1,2315,res,buy,257,۱۳۹۸,2025-10-11,"POLYGON ((538675.089 3962605.612, 538569.174 3..."
4159,رستم آباد,1,1044,res,buy,375,۱۴۰۳,2025-11-10,"POLYGON ((541685.98 3962017.31, 542291.659 396..."
304,رستم آباد,1,295,res,buy,150000000,۱۳۹۰,2024-10-14,"POLYGON ((541685.98 3962017.31, 542291.659 396..."
1583,رستم آباد,1,1446,res,buy,250000000,۱۳۹۶,2024-12-15,"POLYGON ((541685.98 3962017.31, 542291.659 396..."
3669,رستم آباد,1,3029,res,buy,305,۱۳۹۵,2025-11-07,"POLYGON ((541685.98 3962017.31, 542291.659 396..."
212,قيطريه,1,205,res,buy,100000000,۱۳۹۵,2024-10-14,"POLYGON ((539274.909 3961170.25, 539355.64 396..."
5,قيطريه,1,2,res,buy,254166000,۱۴۰۳,2024-12-08,"POLYGON ((539274.909 3961170.25, 539355.64 396..."
1217,قيطريه,1,1148,res,buy,141904000,۱۳۹۴,2024-12-15,"POLYGON ((539274.909 3961170.25, 539355.64 396..."
3731,قيطريه,1,3062,res,buy,198,۱۳۸۷,2025-11-07,"POLYGON ((539274.909 3961170.25, 539355.64 396..."
3978,قيطريه,1,3218,res,buy,205,۱۳۹۵,2025-11-07,"POLYGON ((539274.909 3961170.25, 539355.64 396..."
1405,جوزستان,1,1315,res,buy,400000000,۱۴۰۱,2024-12-15,"POLYGON ((539555.54 3962444.28, 539582.79 3962..."
236,جوزستان,1,228,res,buy,280000000,۱۴۰۰,2024-10-14,"POLYGON ((539555.54 3962444.28, 539582.79 3962..."
217,نياوران,1,209,res,buy,264150000,۱۴۰۲,2024-10-14,"POLYGON ((541873.98 3963174.66, 541690.82 3963..."
2816,نياوران,1,2401,res,buy,227,۱۳۹۵,2025-10-12,"POLYGON ((541873.98 3963174.66, 541690.82 3963..."
241,نياوران,1,233,res,buy,147933000,۱۳۸۴,2024-10-14,"POLYGON ((541873.98 3963174.66, 541690.82 3963..."
1146,نياوران,1,1080,res,buy,250000000,۱۴۰۳,2024-12-15,"POLYGON ((541873.98 3963174.66, 541690.82 3963..."
1149,نياوران,1,1083,res,buy,160000000,۱۳۸۸,2024-12-15,"POLYGON ((541873.98 3963174.66, 541690.82 3963..."
137,نياوران,1,135,res,buy,400000000,۱۴۰۳,2024-10-13,"POLYGON ((541873.98 3963174.66, 541690.82 3963..."
119,نياوران,1,117,res,buy,300000000,۱۴۰۱,2024-10-13,"POLYGON ((541873.98 3963174.66, 541690.82 3963..."
1143,نياوران,1,1077,res,buy,240000000,۱۴۰۲,2024-12-15,"POLYGON ((541873.98 3963174.66, 541690.82 3963..."
2734,کاشانک,1,2314,res,buy,412,۱۴۰۰,2025-10-11,"POLYGON ((543895.19 3961994.8, 543884.15 39619..."
1492,کاشانک,1,1380,res,buy,185714000,۱۳۹۷,2024-12-15,"POLYGON ((543895.19 3961994.8, 543884.15 39619..."
3355,کاشانک,1,2802,res,buy,374,۱۴۰۰,2025-11-07,"POLYGON ((543895.19 3961994.8, 543884.15 39619..."
2193,کاشانک,1,1957,res,buy,210000000,۱۳۸۶,2025-01-07,"POLYGON ((543895.19 3961994.8, 543884.15 39619..."
7,کاشانک,1,4,res,buy,369230000,۱۴۰۳,2024-12-08,"POLYGON ((543895.19 3961994.8, 543884.15 39619..."
228,کاشانک,1,220,res,buy,157407000,۱۳۸۵,2024-10-14,"POLYGON ((543895.19 3961994.8, 543884.15 39619..."
3979,کاشانک,1,3219,res,buy,241,۱۳۸۵,2025-11-07,"POLYGON ((543895.19 3961994.8, 543884.15 39619..."
2175,داراباد,1,1944,res,buy,61855000,۱۳۷۱,2025-01-05,"POLYGON ((544422.757 3964216.251, 544492.43 39..."
1661,داراباد,1,1499,res,buy,196319000,۱۴۰۳,2024-12-15,"POLYGON ((544422.757 3964216.251, 544492.43 39..."
229,حکمت _ دزاشيب,1,221,res,buy,114000000,۱۳۸۵,2024-10-14,"POLYGON ((540907.19 3962498.18, 540911.98 3962..."
3388,امام زاده قاسم,1,2835,res,buy,167,۱۳۹۷,2025-11-07,"POLYGON ((539221.46 3962389.79, 539226.4 39623..."
3365,امام زاده قاسم,1,2811,res,buy,223,۱۳۸۵,2025-11-07,"POLYGON ((539221.46 3962389.79, 539226.4 39623..."
9,ولنجک,1,6,res,buy,305555000,۱۳۹۸,2024-12-08,"POLYGON ((535251.151 3963130.29, 535414.604 39..."
307,ولنجک,1,298,res,buy,239130000,۱۳۸۷,2024-10-14,"POLYGON ((535251.151 3963130.29, 535414.604 39..."
1919,ولنجک,1,1709,res,buy,301526000,۱۴۰۱,2024-12-16,"POLYGON ((535251.151 3963130.29, 535414.604 39..."

In [15]:
q1 = resbuy1.mtrprice.quantile(0.25)
q3 = resbuy1.mtrprice.quantile(0.75)
iqr = q3 - q1
upperLim = q3 + (1.5 * iqr)
lowerLim = q1 - (0.5 * iqr)

result = {
    'Q1': int(q1),
    'Q3': int(q3),
    'IQR': int(iqr),
    'upper limit': int(upperLim),
    'lower limit': int(lowerLim)
}

print(result)

{'Q1': 322, 'Q3': 250000000, 'IQR': 249999677, 'upper limit': 624999516, 'lower limit': -124999516}

In [16]:
resbuy1.query(f'mtrprice >= {upperLim} or mtrprice <= {lowerLim}')

Empty GeoDataFrame
Columns: [NAME_MAHAL, reg_no, index_righ, landuse, ptype, mtrprice, cyear, crdatetime, geometry]
Index: []